baseURL = "http://nazreenpe.github.io/blog/"
title = "Nasreen's Code Blog"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"
publishdir = "dist"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "A blog about the things I learn"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
taxonomyCloudShuffle = true

[params.sidebar]
enable = true
sticky = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","taxonomy_cloud"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = ""
email = ""
facebook = ""
github = "nazreenpe"
gitlab = ""
instagram = ""
linkedin = "nasreen-habeeb-ur-rahiman"
twitter = ""
telegram = ""
google_scholar = ""

[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","codepen","gitlab","linkedin","telegram","google_scholar"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[params.copyright]
prefix = ""
holder = "Nasreen Habeeb Ur Rahiman"
startYear = "2018"
suffix = ""

[permalinks]
page = "/:slug/"
posts = "/:year/:month/:day/:title/"

# [[menu.main]]
# name = "Repo"
# weight = -10
# identifier = "repository"
# url = "https://github.com/nazreenpe/blog"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
